SCRAPING DATA FROM A REAL WEBSITE + PANDAS

In [19]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [30]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
headers = {
    'User-Agent': 'Scraping data project (contacto: sjpablo6a@gmail.com)'}
page = requests.get(url, headers=headers)
if page.status_code == 200:
    soup = BeautifulSoup(page.text, 'html.parser') # Es mejor usar 'html.parser' o 'lxml'
    print("Título de la página:", soup.title.text)
else:
    print(f"Error al acceder: {page.status_code}")

Título de la página: List of largest companies in the United States by revenue - Wikipedia

In [36]:
table = soup.find_all('table')[0]

In [37]:
world_titles = table.find_all('th')

In [38]:
world_table_titles = [title.text.strip() for title in world_titles]
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [39]:
df = pd.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [41]:
column_data = table.find_all('tr')

In [43]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    lenght =  len(df)
    df.loc[lenght] = individual_row_data

In [44]:
 df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Electronics industry,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,The Travelers Companies,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical industry,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [ ]:
df.to_csv(r'C:\Users\57317\Desktop\PROYECTOS PORTAFOLIO')